### ISSUE TITLE
## Todo-list de finalização do sistema:

### ISSUE THREAD

**Issue by BrunoSan123** [BrunoSan123/wp_system#15]
- [x] Criar botão de atualizar credenciais do Gdrive;
- [x]  Adicionar botão de atualizar perfis de Ia, na pagina "Register Ia credential";
- [x] Na listagem de configs, adicionar botão de criar documento do Gdrive e um de importar dados do documento;
- [x] Testar postagem em lotes.
- [x] Estilizar conteúdo das configurações de ia.
- [x] adicionar ícones de load, quando a query estiver acontecendo, uma dica será apenas substituir um icon no botão,por um icon de spinning
- [x]  Eliminar todo código considerado lixo.
- [x]  A página de criar credenciais para o drive,quando clica em criar ou atualizar,não acontece nada,deveria ter um reload na página, ou um alert avisando que os dados foram salvos ou atualizados.
- [x] faltou eliminar a view, "Criar no Google Docs"
- [x] faltou criar o botão de consumir conteúdo do post, se baseie no nos forms da view "Criar no Google Docs"
- [x]  Ao clicar do botão de criar documento no drive,não há nenhuma indicação de que a query está acontecendo,sugiro botar o mesmo display que eu tinha visto ao postar no wordpress, o mesmo vale para a geração de conteúdo com gpt.
- [x]  atualizar o Js o do botão de criar documento do google, para emitir um alert caso a url salva seja invalida.
- [x]  foi adicionado um novo campo a tabela post_content, o campo "Gdrive_url", está sendo usado para armazenar a pasta do drive que contem apenas imagens. O gdrive_document_url é que será usado para armazenar a url com pastar e documentos. Na view "criar post", deve se adicionar um campo referente a isso "gdrive_document_url".
- [x] faltou adicionar ícones de load em alguns botões, como o do Gerar conteúdo,assim como faltou dar reload em alguns alerts após clicar em "Continue".
- [x]  quando clica no botão de sair, se tem um erro. Averiguar o que pode estar acontecendo.
- [x]  existe um bug estranho no login do google,ele gera o token e armazena na sessão,porém em prod, não tá fazendo fazendo o redirecionamento correto,ele redireciona para o auth novamente. Averiguar isso.
- [x] tinha uma função chamada "loading_elements que quando fui testar tava dando 'undefined', não sei o por que,mas é bom averiguar"
- [x]  No botão de gerar em demanda, faltou botar a query que atualiza o yoaust, tem só a query que faz a postagem.
- [x] Seria bom adicionar um botão de deletar em massa.
- [x]  Gostaria que fosse adicionado um botão de atualizar na página de configurações da Ia

**Comment by BrunoSan123** [comment]
passei um bom tempo debugando esse lance do redirect, e estava acontecendo porque em prod não tá sendo gerado o refresh_token, ai caia no catch que fazia um redirect para o auth. Porém em dev, tá sendo gerado o refresh_token. Pesquisei, e aparentemente isso é devido a um na sua conta google. sai de alguns aplicativos na minha conta e uma hora ele conseguiu gerar o refresh_token. Porém como fui testar acabou não criando de novo. Enfim, parece algo muito particular ligado ao modo de verificação. queria que vc testasse isso também. botei para retornar o erro ao invés do redirect. Esse é o link para tentar gerenciar seus acessos:

https://myaccount.google.com/
